Repository kubernetes-sigs/cli-utils, pull requests merged in 2020-11, with the labels that each got.

#268 Fixes namespace calculation for cluster-scoped resources
  pkg/config/initoptions.go
  pkg/config/initoptions_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#269 Adds more server-side flags to preview command
  cmd/preview/cmdpreview.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#271 Moves destroyer Initialize() to immediately before Run()
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#264 split inventory and resources in the apply interface
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/prune_task.go
  pkg/inventory/inventory.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#272 Verifies interfaces Provider and ManifestReader are satisfied
  pkg/manifestreader/path.go
  pkg/manifestreader/stream.go
  pkg/provider/provider.go
Labels: approved, cncf-cla: yes, size/XS

#275 No prune for namespaces that contain current objects
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#273 add the new lifecycle annotation for deletion
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/common/common.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#277 update kubectl to 1.18.10
  cmd/diff/cmddiff.go
  go.mod
  go.sum
  pkg/apply/prune/prune.go
  pkg/apply/task/apply_task.go
  pkg/common/common.go
  pkg/inventory/inventory-client.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#278 Pin to kyaml v0.9.4
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/XS

#270 change the apply interface to use inventory.InventoryInfo
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  cmd/status/cmdstatus.go
  cmd/status/cmdstatus_test.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/prune_task.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
  pkg/inventory/inventory-info.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_test.go
  pkg/inventory/inventorycm.go
  pkg/manifestreader/fake-loader.go
  pkg/manifestreader/manifestloader.go
  pkg/provider/fake-provider.go
  pkg/provider/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#280 inventory client replace skipped in dry-run
  go.sum
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#281 update events to include indentifier and error
  cmd/printers/events/formatter_test.go
  cmd/printers/json/formatter_test.go
  pkg/apply/event/applyeventtype_string.go
  pkg/apply/event/deleteeventtype_string.go
  pkg/apply/event/event.go
  pkg/apply/event/pruneeventtype_string.go
  pkg/apply/prune/prune.go
  pkg/apply/task/printer_adapter.go
  pkg/apply/task/printer_adapter_test.go
  pkg/object/objmetadata.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#283 change prune to be continue on error
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#285 Adds e2e test for init command
  examples/alphaTestExamples/init.md
  pkg/config/initoptions.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#284 Adds end-to-end test for pruning and namespaces
  examples/alphaTestExamples/pruneNamespace.md
  pkg/apply/prune/prune.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#287 catch up the change in PruneEvent during destroy
  cmd/printers/events/formatter.go
  pkg/apply/destroyer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#286 change apply to continue on error
  pkg/apply/applier_test.go
  pkg/apply/error/error.go
  pkg/apply/event/applyeventtype_string.go
  pkg/apply/event/event.go
  pkg/apply/info/info_helper.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/inventory/inventory-client.go
Labels: approved, cncf-cla: yes, lgtm, size/L
