Repository kubernetes-sigs/cli-utils, pull requests merged in 2020-02, with the labels that each got.

#17 Add makefile, include it in travis build and fix linting errors
  .golangci.yml
  .travis.yml
  Makefile
  cmd/common/commands.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/basic_printer.go
  pkg/apply/prune/grouping.go
  pkg/apply/prune/grouping_test.go
  pkg/apply/prune/inventory.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#18 Adds file comments to grouping.go
  .gitignore
  pkg/apply/prune/grouping.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/XS

#20 Renames Inventory to ObjMetadata; InventorySet to Inventory
  LICENSE_TEMPLATE
  Makefile
  go.sum
  pkg/apply/prune/grouping.go
  pkg/apply/prune/grouping_test.go
  pkg/apply/prune/inventory.go
  pkg/apply/prune/inventory_test.go
  pkg/apply/prune/objmetadata.go
  pkg/apply/prune/objmetadata_test.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/XXL

#23 Restructure the cobra commands
  .gitignore
  Makefile
  cmd/apply/cmdapply.go
  cmd/diff/cmddiff.go
  cmd/kapply/kapply.go
  cmd/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#22 Integrate prune with the applier
  pkg/apply/applier.go
  pkg/apply/prune/prune.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#24 Add missing import for auth
  cmd/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#25 Adds file license to several files.
  cmd/apply/cmdapply.go
  cmd/diff/cmddiff.go
  cmd/main.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/XS

#21 Connect dry-run flag to prune delete; Add no-prune flag
  cmd/apply/cmdapply.go
  pkg/apply/applier.go
  pkg/apply/prune/prune.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/M

#16 E2E tests framework for kapply
  Makefile
  examples/alphaTestExamples/helloapp.md
  hack/testExamplesE2EAgainstKapply.sh
Labels: cncf-cla: yes, lgtm, size/L

#30 Adds first version of Preview command
  cmd/main.go
  cmd/preview/cmdpreview.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/M

#26 Fixes case where some resources evolve from extensions group
  pkg/apply/prune/objmetadata.go
  pkg/apply/prune/objmetadata_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/M

#31 Move the PrependGroupingObject function into the prune package
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/prune/grouping.go
  pkg/apply/prune/grouping_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#33 Prune not exit when deletion item not found
  pkg/apply/prune/prune.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/XS

#28 Destroy command
  .travis.yml
  cmd/destroy/cmddestroy.go
  cmd/main.go
  examples/alphaTestExamples/helloapp.md
  pkg/apply/destroyer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#19 New observer library for status and new status command
  go.mod
  go.sum
  pkg/kstatus/observe/event/event.go
  pkg/kstatus/observe/event/event_test.go
  pkg/kstatus/observe/observer/aggregator.go
  pkg/kstatus/observe/observer/observer.go
  pkg/kstatus/observe/observer/observer_test.go
  pkg/kstatus/observe/observer/reader.go
  pkg/kstatus/observe/observer/resourceobserver.go
  pkg/kstatus/observe/testutil/testing.go
  pkg/kstatus/status/status.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#32 Use channel directly in prune instead of ToPrinter
  pkg/apply/applier.go
  pkg/apply/basic_printer.go
  pkg/apply/event/event.go
  pkg/apply/printer_adapter.go
  pkg/apply/printer_adapter_test.go
  pkg/apply/prune/prune.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#34 Updated comments and small fixes
  pkg/kstatus/observe/event/event.go
  pkg/kstatus/observe/event/event_test.go
  pkg/kstatus/observe/event/eventtype_string.go
  pkg/kstatus/observe/observer/aggregator.go
  pkg/kstatus/observe/observer/observer.go
  pkg/kstatus/observe/observer/observer_test.go
  pkg/kstatus/observe/observer/reader.go
  pkg/kstatus/observe/testutil/testing.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#39 Updates destroyer to use Prune with channel
  pkg/apply/destroyer.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/S

#42 Add prow target to Makefile
  Makefile
Labels: cncf-cla: yes, size/XS

#40 Clear current grouping object before prune in destroyer
  pkg/apply/destroyer.go
  pkg/apply/prune/grouping.go
  pkg/apply/prune/grouping_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, sig/cli, size/M

#27 Remove the -f and -k flags for apply
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/path.go
  pkg/apply/path_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#36 Implementations of the ObserverReader interface for the Observe frame…
  pkg/kstatus/observe/reader/caching_reader.go
  pkg/kstatus/observe/reader/caching_reader_test.go
  pkg/kstatus/observe/reader/direct_reader.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#43 Remove/hide unused flags for kapply commands
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/destroyer.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/M

#35 Aggregator implementation for the Observe framework
  pkg/kstatus/observe/aggregator/aggregator.go
  pkg/kstatus/observe/aggregator/aggregator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#41 Remove -f -k from destroy and E2e tests for kapply commands
  cmd/destroy/cmddestroy.go
  examples/alphaTestExamples/MultipleServcies.md
  examples/alphaTestExamples/helloapp.md
  hack/testExamplesE2EAgainstKapply.sh
  pkg/apply/destroyer.go
Labels: cncf-cla: yes, lgtm, size/L

#44 Rename interface from ObserverReader to ClusterReader
  pkg/kstatus/observe/observer/observer.go
  pkg/kstatus/observe/observer/observer_test.go
  pkg/kstatus/observe/observer/reader.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#48 Check for presence of grouping object before applying resources
  pkg/apply/prune/grouping.go
  pkg/apply/prune/grouping_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#46 Order resources for apply
  examples/alphaTestExamples/helloapp.md
  pkg/apply/applier.go
  pkg/apply/event/event.go
  pkg/apply/path.go
  pkg/apply/path_test.go
  pkg/apply/resource_infos.go
  pkg/apply/resource_infos_test.go
  pkg/kstatus/observe/aggregator/aggregator.go
  pkg/kstatus/observe/aggregator/aggregator_test.go
  pkg/kstatus/observe/event/event.go
  pkg/kstatus/observe/event/event_test.go
  pkg/kstatus/observe/event/eventtype_string.go
  pkg/kstatus/observe/observer/aggregator.go
  pkg/kstatus/observe/observer/observer.go
  pkg/kstatus/observe/observer/observer_test.go
  pkg/kstatus/observe/observer/reader.go
  pkg/kstatus/observe/observer/resourceobserver.go
  pkg/kstatus/observe/reader/caching_reader.go
  pkg/kstatus/observe/reader/caching_reader_test.go
  pkg/kstatus/observe/reader/direct_reader.go
  pkg/kstatus/observe/testutil/testing.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#50 Hides server-side and record flags.
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/destroyer.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/M

#47 New events that signal when all resources have been applied and pruned
  pkg/apply/applier.go
  pkg/apply/basic_printer.go
  pkg/apply/destroyer.go
  pkg/apply/event/applyeventoperation_string.go
  pkg/apply/event/applyeventtype_string.go
  pkg/apply/event/deleteeventtype_string.go
  pkg/apply/event/event.go
  pkg/apply/event/pruneeventtype_string.go
  pkg/apply/event/type_string.go
  pkg/apply/printer_adapter.go
  pkg/apply/printer_adapter_test.go
  pkg/apply/prune/prune.go
  pkg/kstatus/observe/event/eventtype_string.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#37 ResourceObservers for the Observe framework
  pkg/kstatus/observe/observers/common.go
  pkg/kstatus/observe/observers/common_test.go
  pkg/kstatus/observe/observers/default.go
  pkg/kstatus/observe/observers/default_test.go
  pkg/kstatus/observe/observers/deployment.go
  pkg/kstatus/observe/observers/deployment_test.go
  pkg/kstatus/observe/observers/replicaset.go
  pkg/kstatus/observe/observers/replicaset_test.go
  pkg/kstatus/observe/observers/statefulset.go
  pkg/kstatus/observe/observers/statefulset_test.go
  pkg/kstatus/observe/observers/testing.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#52 Fix files that are missing license info
  pkg/apply/event/applyeventoperation_string.go
  pkg/apply/event/applyeventtype_string.go
  pkg/apply/event/deleteeventtype_string.go
  pkg/apply/event/pruneeventtype_string.go
  pkg/apply/event/type_string.go
  pkg/kstatus/observe/event/eventtype_string.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#53 Fixes destroy command crash when dry-run flag not defined
  cmd/destroy/cmddestroy.go
Labels: approved, cncf-cla: yes, priority/important-soon, sig/cli, size/XS

#51 Rename DefaultObserver to genericObserver
  pkg/kstatus/observe/observers/common.go
  pkg/kstatus/observe/observers/common_test.go
  pkg/kstatus/observe/observers/deployment.go
  pkg/kstatus/observe/observers/deployment_test.go
  pkg/kstatus/observe/observers/generic.go
  pkg/kstatus/observe/observers/generic_test.go
  pkg/kstatus/observe/observers/replicaset.go
  pkg/kstatus/observe/observers/replicaset_test.go
  pkg/kstatus/observe/observers/statefulset.go
  pkg/kstatus/observe/observers/statefulset_test.go
  pkg/kstatus/observe/observers/testing.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#54 Update the flags used to enable and configure wait for status in applier
  examples/alphaTestExamples/MultipleServcies.md
  examples/alphaTestExamples/helloapp.md
  pkg/apply/status.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#58 Add linter to prow make target
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#57 Destroy flag for preview
  cmd/preview/cmdpreview.go
  examples/alphaTestExamples/MultipleServcies.md
  examples/alphaTestExamples/helloapp.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, priority/important-soon, sig/cli, size/M

#59 Update outdated comment
  pkg/kstatus/observe/observers/common.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#60 Remove arg count check from destroy command
  cmd/destroy/cmddestroy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#62 Disable travis in favor of prow.
  hack/old_dot_travis
Labels: approved, cncf-cla: yes, lgtm, size/XS

#38 Collector to help consumers of the Observer library
  pkg/kstatus/observe/collector/collector.go
  pkg/kstatus/observe/collector/collector_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#45 Unit test for Applier
  pkg/apply/applier_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#64 Latest version of stringer for go generate
  go.mod
  go.sum
  pkg/kstatus/observe/collector/collector.go
  pkg/kstatus/observe/collector/collector_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/S

#65 Check for missing license header in presubmit
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#56 Add main entrypoint for the observer library
  pkg/kstatus/observe/doc.go
  pkg/kstatus/observe/observe.go
Labels: approved, cncf-cla: yes, size/L

#66 Fix missing license header
  pkg/kstatus/observe/observe.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#61 Improve status for pods
  pkg/kstatus/status/core.go
  pkg/kstatus/status/status_augment_test.go
  pkg/kstatus/status/status_compute_test.go
  pkg/kstatus/status/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#68 Turn off default kubectl prune
  pkg/apply/applier.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/XS

#69 Adds NoGroupingObjError with detailed error message
  pkg/apply/prune/grouping.go
  pkg/apply/prune/no_grouping_error.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/M

#70 Handle errors from reading manifests
  pkg/apply/applier.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#71 Handle errors from reading manifests in Destroyer
  pkg/apply/destroyer.go
Labels: approved, cncf-cla: yes, lgtm, size/S
