Repository kubernetes-sigs/cli-utils, pull requests merged in 2020-04, with the labels that each got.

#115 Updates go.mod to use latest kyaml (v0.1.4)
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/S

#114 Change grouping object to inventory object
  cmd/initcmd/cmdinit.go
  pkg/config/initoptions.go
  pkg/config/initoptions_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#118 fix broken link:https://git.k8s.io/community/contributors/guide/contr…
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#113 Updates prune to use UID instead of ObjMetadata
  pkg/apply/applier.go
  pkg/apply/destroyer.go
  pkg/apply/prune/grouping_test.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/object/objmetadata.go
  pkg/object/objmetadata_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, sig/cli, size/L

#119 Fix handling of clusterscoped resources in status poller
  pkg/apply/applier.go
  pkg/kstatus/polling/engine/engine.go
  pkg/kstatus/polling/engine/engine_test.go
  pkg/kstatus/polling/statusreaders/common.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#111 Status poller should poll immediate regardles of polling interval
  pkg/kstatus/polling/engine/engine.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#120 Add support for supporting multiple print formats for apply
  cmd/apply/cmdapply.go
  cmd/printers/printer/printer.go
  cmd/printers/printers.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#121 add json tag to Condition type
  pkg/kstatus/status/status.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#122 Break out functionality for table printing into library
  pkg/print/common/ansii.go
  pkg/print/common/color.go
  pkg/print/common/color_test.go
  pkg/print/table/base.go
  pkg/print/table/base_test.go
  pkg/print/table/columndefs.go
  pkg/print/table/columndefs_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#109 Use Ready condition for computing status if it is available on a resource
  pkg/kstatus/README.md
  pkg/kstatus/status/status.go
  pkg/kstatus/status/status_compute_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#126 Removes duplicate import; cleans up comment
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#125 cli-utils diff command with one directory argument
  cmd/diff/cmddiff.go
  pkg/apply/applier.go
  pkg/apply/destroyer.go
  pkg/common/path.go
  pkg/common/path_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#127 Only send status events if we are waiting for reconcile
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/status.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/runner_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#123 Add new table format printer for apply
  cmd/printers/printers.go
  cmd/printers/table/collector.go
  cmd/printers/table/printer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#128 Remove aggregator from polling engine
  cmd/status/printers/table_printer.go
  cmd/status/status.go
  pkg/apply/applier_test.go
  pkg/apply/taskrunner/runner.go
  pkg/kstatus/polling/aggregator/aggregator.go
  pkg/kstatus/polling/aggregator/aggregator_test.go
  pkg/kstatus/polling/collector/collector.go
  pkg/kstatus/polling/collector/collector_test.go
  pkg/kstatus/polling/engine/aggregator.go
  pkg/kstatus/polling/engine/engine.go
  pkg/kstatus/polling/engine/engine_test.go
  pkg/kstatus/polling/event/event.go
  pkg/kstatus/polling/polling.go
  pkg/kstatus/polling/polling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#117 Use the Go race detector for unit tests and e2e tests
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#129 Expand package dir configs; exclude inventory object
  cmd/diff/cmddiff.go
  pkg/common/path.go
  pkg/common/path_test.go
Labels: approved, cncf-cla: yes, size/M

#116 Add TaskContext to be passed between tasks
  pkg/apply/applier.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/prune_task.go
  pkg/apply/task/send_event_task.go
  pkg/apply/taskrunner/context.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/runner_test.go
  pkg/apply/taskrunner/task.go
  pkg/apply/taskrunner/task_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#132 Adds a Test Filesystem in testutils; adds some tests to use it
  pkg/common/path_test.go
  pkg/testutil/test-filesystem.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#130 Handle unknown types in APIServer in polling engine
  go.mod
  go.sum
  pkg/kstatus/polling/clusterreader/caching_reader.go
  pkg/kstatus/polling/clusterreader/caching_reader_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#131 Use BaseTablePrinter in status command
  cmd/status/printers/adapter.go
  cmd/status/printers/color.go
  cmd/status/printers/printers.go
  cmd/status/printers/table_printer.go
  cmd/status/status.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#133 Fix govet issue
  pkg/kstatus/polling/engine/engine_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#134 Polling library should send update when resource gen changes
  pkg/kstatus/polling/engine/engine.go
  pkg/kstatus/polling/event/event.go
  pkg/kstatus/polling/event/event_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#136 Fix hidden wait flag
  pkg/apply/applier.go
  pkg/apply/destroyer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#135 Use resource generation in status decisions
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/taskrunner/collector.go
  pkg/apply/taskrunner/collector_test.go
  pkg/apply/taskrunner/context.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/task.go
  pkg/object/objmetadata.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#137 Wait for CRDs to become established before applying CRs
  pkg/apply/applier.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/object/objmetadata.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#138 Remove wait flags from the preview command
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/status.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#139 Handle errors better in table views
  cmd/printers/table/collector.go
  cmd/printers/table/printer.go
  cmd/status/printers/adapter.go
  pkg/print/table/base.go
  pkg/print/table/base_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#140 Status for dep, sts and rs should be InProgress if extra replicas
  pkg/kstatus/status/core.go
  pkg/kstatus/status/status_compute_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#141 Support for prune in the table view
  cmd/printers/table/collector.go
  cmd/printers/table/collector_test.go
  cmd/printers/table/printer.go
  cmd/printers/table/printer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#145 Moves some grouping names to inventory
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/prune/grouping.go
  pkg/apply/prune/grouping_test.go
  pkg/apply/prune/prune.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#144 Removes inventory.go and inventory_test.go
  pkg/apply/prune/inventory.go
  pkg/apply/prune/inventory_test.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#146 Moves GroupingLabel/Hash to InventoryLabel/Hash in common
  cmd/status/util.go
  pkg/apply/applier_test.go
  pkg/apply/prune/grouping.go
  pkg/apply/prune/grouping_test.go
  pkg/apply/prune/prune.go
  pkg/common/common.go
  pkg/common/path.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#147 Renames grouping.go to inventory.go
  pkg/apply/applier.go
  pkg/apply/prune/inventory.go
  pkg/apply/prune/inventory_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#148 Remove DryRun and NoPrune fields on Applier and PruneOptions
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/prune_task.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#143 Add StdIn as an acceptable argument for apply, preview, destroy, and diff commands
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/diff/cmddiff.go
  cmd/preview/cmdpreview.go
  pkg/common/path.go
  pkg/common/path_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#149 Move grouping errors to inventory errors
  pkg/apply/applier.go
  pkg/apply/prune/inventory_error.go
  pkg/apply/prune/no_grouping_error.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#150 Grouping object to inventory object cleanup
  pkg/apply/applier_test.go
  pkg/apply/prune/inventory.go
  pkg/apply/prune/inventory_test.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#151 Rename grouping to inventory in applier
  pkg/apply/applier.go
  pkg/apply/applier_test.go
Labels: approved, cncf-cla: yes, size/M
