Repository kubernetes-sigs/cli-utils, pull requests merged in 2020-10, with the labels that each got.

#247 Upgrade to kyaml v0.9.0
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/XS

#248 Update to the latest version of golint
  Makefile
  cmd/printers/json/formatter_test.go
  go.mod
  go.sum
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/task.go
  pkg/common/common.go
  pkg/kstatus/status/core.go
  pkg/kstatus/status/status.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#249 Pin to kyaml v0.9.1
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS

#250 Stores InventoryClient in FakeProvider
  pkg/provider/fake-provider.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#252 Pin to kyaml v0.9.2
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/XS

#246 Move ApplyOptions into ApplyTask
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/info/info_helper.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#254 Remove IOStreams from the Applier
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#256 Clean up go mod
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#253 Clean up the event hierarchy
  cmd/printers/events/formatter.go
  cmd/printers/events/formatter_test.go
  cmd/printers/json/formatter.go
  cmd/printers/json/formatter_test.go
  cmd/printers/table/collector.go
  pkg/apply/applier_test.go
  pkg/apply/event/applyeventoperation_string.go
  pkg/apply/event/applyeventtype_string.go
  pkg/apply/event/deleteeventoperation_string.go
  pkg/apply/event/deleteeventtype_string.go
  pkg/apply/event/event.go
  pkg/apply/event/pruneeventoperation_string.go
  pkg/apply/event/pruneeventtype_string.go
  pkg/apply/event/resourceaction_string.go
  pkg/apply/event/statuseventtype_string.go
  pkg/apply/event/type_string.go
  pkg/apply/solver/solver.go
  pkg/apply/taskrunner/runner.go
  pkg/kstatus/polling/engine/engine.go
  pkg/kstatus/polling/engine/engine_test.go
  pkg/kstatus/polling/event/event.go
  pkg/kstatus/polling/event/eventtype_string.go
  pkg/print/list/base.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#258 Use Unstructured instead of Info
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
  examples/alphaTestExamples/inventoryNamespace.md
  hack/testExamplesE2EAgainstKapply.sh
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/info/info_helper.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/task/prune_task.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_error.go
  pkg/inventory/inventory_test.go
  pkg/manifestreader/common.go
  pkg/object/infos.go
  pkg/object/objmetadata.go
  pkg/ordering/sort.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#259 Change PruneOptions and Destroyer to use Unstructured instead of Info
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/task/prune_task.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#260 Remove resource.Info from inventory package
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  cmd/status/cmdstatus.go
  pkg/apply/applier.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_test.go
  pkg/inventory/inventorycm.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#257 Implements server-side apply
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
  examples/alphaTestExamples/serverSideApply.md
  pkg/apply/applier.go
  pkg/apply/event/applyeventoperation_string.go
  pkg/apply/event/applyeventtype_string.go
  pkg/apply/event/deleteeventoperation_string.go
  pkg/apply/event/deleteeventtype_string.go
  pkg/apply/event/pruneeventoperation_string.go
  pkg/apply/event/pruneeventtype_string.go
  pkg/apply/event/resourceaction_string.go
  pkg/apply/event/statuseventtype_string.go
  pkg/apply/event/type_string.go
  pkg/apply/solver/solver.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/common/common.go
  pkg/kstatus/polling/event/eventtype_string.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#261 Update the ManifestReader interface and implementations to use Unstructured
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  cmd/status/cmdstatus.go
  pkg/apply/applier.go
  pkg/apply/info/info_helper.go
  pkg/apply/task/apply_task_test.go
  pkg/manifestreader/common.go
  pkg/manifestreader/common_test.go
  pkg/manifestreader/manifestreader.go
  pkg/manifestreader/path.go
  pkg/manifestreader/path_test.go
  pkg/manifestreader/stream.go
  pkg/manifestreader/stream_test.go
  pkg/manifestreader/testdata.go
  pkg/object/infos.go
  pkg/object/infos_test.go
  pkg/provider/fake-provider.go
  pkg/provider/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#262 Export ExpandDir function and add an extra return value
  pkg/common/path.go
  pkg/common/path_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#265 Pin to kyaml v0.9.3
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#263 Add output flag to destroy and preview commands
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
