Repository kubernetes-sigs/cli-utils, pull requests merged in 2020-07, with the labels that each got.

#198 Fail Apply/Preview for Required Setters
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#199 Bump kyaml version to 0.4.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/S

#203 Validates resource names before storing in inventory
  pkg/object/objmetadata.go
  pkg/object/objmetadata_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#204 Added parsing to objmetadata_test.TestCreateObjMetadata
  pkg/object/objmetadata_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#207 Prune/destroy resources in reverse order from apply
  pkg/apply/applier.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/ordering/sort.go
  pkg/ordering/sort_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#205 namespaced kpt live init
  cmd/initcmd/cmdinit.go
  examples/alphaTestExamples/MultipleServices.md
  examples/alphaTestExamples/pruneAndDelete.md
  pkg/config/initoptions.go
  pkg/config/initoptions_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#194 Updates prune algorithm to use one inventory object
  examples/alphaTestExamples/MultipleServices.md
  examples/alphaTestExamples/helloapp.md
  go.sum
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/config/initoptions.go
  pkg/config/initoptions_test.go
  pkg/inventory/fake-builder.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_test.go
  pkg/inventory/inventorycm.go
  pkg/object/objmetadata.go
  pkg/object/objmetadata_test.go
  pkg/ordering/sort.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
