Repository kubernetes-sigs/cli-utils, pull requests merged in 2020-05, with the labels that each got.

#154 Renamed grouping to inventory
  pkg/apply/prune/inventory_test.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#155 Allow users to specify deletion propagation for prune
  cmd/apply/cmdapply.go
  pkg/apply/applier.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/solver/solver.go
  pkg/apply/task/prune_task.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#157 Fix issue where dry-run ends up making changes
  pkg/apply/solver/solver.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#158 More checks in E2E tests
  examples/alphaTestExamples/helloapp.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#160 Improve the MultipleServices E2E tests
  examples/alphaTestExamples/MultipleServices.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#159 Never delete lifecycle directive
  pkg/apply/basic_printer.go
  pkg/apply/event/event.go
  pkg/apply/event/pruneeventtype_string.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/common/common.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#162 Propagate kubeconfig flags to subcommands
  cmd/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#163 Cleanup grouping nomenclature as inventory
  cmd/initcmd/cmdinit.go
  cmd/status/util.go
  pkg/apply/destroyer.go
  pkg/object/objmetadata.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#164 Initial basic README for cli-utils release
  release/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#156 Print more info on wait timeout
  cmd/printers/table/collector.go
  pkg/apply/taskrunner/collector.go
  pkg/apply/taskrunner/collector_test.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/task.go
  pkg/apply/taskrunner/task_test.go
  pkg/print/table/base.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#142 Support wait for prune in the applier
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/prune/inventory.go
  pkg/apply/prune/inventory_test.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#166 Print more info on wait timeout for basicprinter
  cmd/printers/table/collector.go
  pkg/apply/basic_printer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#161 Adds klog to kapply; initial log statements in prune
  cmd/main.go
  go.mod
  pkg/apply/prune/prune.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#152 Polling package should handle missing resource types in RESTMapper
  pkg/kstatus/polling/clusterreader/caching_reader.go
  pkg/kstatus/polling/clusterreader/caching_reader_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#153 Handle CRDs and CRs in the same set of resources
  cmd/main.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/info/info_helper.go
  pkg/apply/solver/solver.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/kstatus/polling/engine/engine.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#168 Add flags for waiting for pruned resources to be deleted
  cmd/apply/cmdapply.go
  pkg/apply/applier.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#165 E2E-test to verify apply with CRD and CR
  examples/alphaTestExamples/crds.md
Labels: approved, cncf-cla: yes, size/L

#172 Move CachingRESTClientGetter into its own package
  cmd/main.go
  pkg/util/factory/clientgetter.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#174 Reduce the number of flags for apply and improve the naming
  cmd/apply/cmdapply.go
  examples/alphaTestExamples/MultipleServices.md
  examples/alphaTestExamples/crds.md
  examples/alphaTestExamples/helloapp.md
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#176 Handle dryrun when applying CRDs
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#179 Disallow stdin as input for diff command
  cmd/diff/cmddiff.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#173 Make Poller property on Applier public to allow Custom poller implementation
  pkg/apply/applier.go
  pkg/apply/applier_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#180 Fix output from lifecycle directive with the destroy command
  cmd/printers/table/collector.go
  cmd/printers/table/printer.go
  cmd/printers/table/printer_test.go
  examples/alphaTestExamples/pruneAndDelete.md
  pkg/apply/basic_printer.go
  pkg/apply/destroyer.go
  pkg/apply/event/deleteeventoperation_string.go
  pkg/apply/event/event.go
  pkg/apply/event/pruneeventoperation_string.go
  pkg/apply/event/pruneeventtype_string.go
  pkg/apply/prune/prune.go
Labels: approved, cncf-cla: yes, lgtm, size/L
