Repository kubernetes-sigs/cli-utils, pull requests merged in 2020-09, with the labels that each got.

#227 New Provider wraps kubectl factory and inventory client
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  cmd/status/cmdstatus.go
  cmd/status/cmdstatus_test.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
  pkg/provider/fake-provider.go
  pkg/provider/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#230 Remove the AbortedEvent from kstatus
  pkg/apply/basic_printer.go
  pkg/kstatus/polling/event/event.go
  pkg/kstatus/polling/event/eventtype_string.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#231 JSON printer for apply
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  cmd/printers/events/formatter.go
  cmd/printers/events/formatter_test.go
  cmd/printers/events/printer.go
  cmd/printers/json/doc.go
  cmd/printers/json/formatter.go
  cmd/printers/json/formatter_test.go
  cmd/printers/json/printer.go
  cmd/printers/printers.go
  pkg/print/list/base.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#225 Handle the --namespace flag
  cmd/apply/cmdapply.go
  cmd/initcmd/cmdinit.go
  cmd/main.go
  cmd/preview/cmdpreview.go
  pkg/config/initoptions.go
  pkg/config/initoptions_test.go
  pkg/manifestreader/common.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#233 Applies inventory namespace first if necessary
  examples/alphaTestExamples/inventoryNamespace.md
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/object/objmetadata.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#226 Handle local config annotation
  pkg/config/initoptions.go
  pkg/config/initoptions_test.go
  pkg/manifestreader/common.go
  pkg/manifestreader/common_test.go
  pkg/manifestreader/path.go
  pkg/manifestreader/stream.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#236 Upgrade to kyaml v0.8.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#238 Pin to kyaml v0.8.1
  go.mod
Labels: cncf-cla: yes, size/XS

#240 Delete BasicPrinter which is no longer in use
  go.sum
  pkg/apply/basic_printer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#239 Expose common functions used by ManifestReader
  go.sum
  pkg/manifestreader/common.go
  pkg/manifestreader/common_test.go
  pkg/manifestreader/manifestreader.go
  pkg/manifestreader/path.go
  pkg/manifestreader/stream.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#237 Install stringer in generate target
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#235 Move ManifestReader creation into Provider
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  cmd/status/cmdstatus.go
  pkg/apply/destroyer.go
  pkg/provider/fake-provider.go
  pkg/provider/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#242 Export some init functions for reuse
  pkg/config/initoptions.go
  pkg/config/initoptions_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#243 Provider can now return error for ManifestReader creation
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  cmd/status/cmdstatus.go
  pkg/provider/fake-provider.go
  pkg/provider/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#241 Use the TaskContext for passing UIDs of applied resources to the pruner
  pkg/apply/applier.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/task/prune_task.go
  pkg/apply/taskrunner/context.go
  pkg/apply/taskrunner/task.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#244 Exports IsDir function with cleanup
  pkg/common/path.go
  pkg/config/initoptions.go
Labels: approved, cncf-cla: yes, lgtm, size/S
