Repository kubernetes-sigs/cli-utils, pull requests merged in 2020-03, with the labels that each got.

#77 Add count of how many resources have been applied/pruned/deleted in the output
  pkg/apply/basic_printer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#79 Add preview suffix
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  examples/alphaTestExamples/helloapp.md
  pkg/apply/basic_printer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#81 apply, preview and destroy take exactly one dir arg
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  go.mod
  go.sum
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/path.go
  pkg/apply/path_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#82 First version of InitOptions and tests
  go.mod
  go.sum
  pkg/config/initoptions.go
  pkg/config/initoptions_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/L

#83 First version of kapply init command
  cmd/initcmd/cmdinit.go
  cmd/main.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/M

#84 Use current grouping object namespace in prune
  pkg/apply/applier.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
Labels: approved, cncf-cla: yes, priority/important-soon, sig/cli, size/S

#85 Ensures all applied objects are in the same namespace
  pkg/apply/applier.go
  pkg/apply/applier_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/L

#86 Update no grouping object error message
  pkg/apply/prune/no_grouping_error.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/S

#88 Adds warning to fields in auto-generated grouping object
  pkg/config/initoptions.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/XS

#72 Better support for aggregators on deletion
  pkg/kstatus/polling/aggregator/aggregator.go
  pkg/kstatus/polling/aggregator/aggregator_test.go
  pkg/kstatus/polling/engine/engine.go
  pkg/kstatus/polling/engine/engine_test.go
  pkg/kstatus/polling/polling.go
Labels: approved, cncf-cla: yes, lgtm, sig/cli, size/L

#89 Added more comments to auto-generated grouping object template file
  pkg/config/initoptions.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/S

#74 Remove wait package
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/basic_printer.go
  pkg/apply/event/event.go
  pkg/apply/prune/grouping.go
  pkg/apply/prune/grouping_test.go
  pkg/apply/prune/inventory.go
  pkg/apply/prune/inventory_test.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/kstatus/polling/aggregator/aggregator.go
  pkg/kstatus/polling/aggregator/aggregator_test.go
  pkg/kstatus/polling/clusterreader/caching_reader.go
  pkg/kstatus/polling/clusterreader/caching_reader_test.go
  pkg/kstatus/polling/collector/collector.go
  pkg/kstatus/polling/collector/collector_test.go
  pkg/kstatus/polling/doc.go
  pkg/kstatus/polling/engine/engine.go
  pkg/kstatus/polling/engine/engine_test.go
  pkg/kstatus/polling/engine/status_reader.go
  pkg/kstatus/polling/event/event.go
  pkg/kstatus/polling/event/event_test.go
  pkg/kstatus/polling/polling.go
  pkg/kstatus/polling/statusreaders/common.go
  pkg/kstatus/polling/statusreaders/common_test.go
  pkg/kstatus/polling/statusreaders/deployment.go
  pkg/kstatus/polling/statusreaders/generic.go
  pkg/kstatus/polling/statusreaders/generic_test.go
  pkg/kstatus/polling/statusreaders/replicaset.go
  pkg/kstatus/polling/statusreaders/statefulset.go
  pkg/kstatus/polling/statusreaders/testing.go
  pkg/kstatus/wait/doc.go
  pkg/kstatus/wait/util.go
  pkg/kstatus/wait/wait.go
  pkg/kstatus/wait/wait_test.go
  pkg/kstatus/wait/waitstate.go
  pkg/object/objmetadata.go
  pkg/object/objmetadata_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/cli, size/XXL

#78 Use the new standard conditions
  pkg/kstatus/status/core.go
  pkg/kstatus/status/generic.go
  pkg/kstatus/status/status.go
  pkg/kstatus/status/status_augment_test.go
  pkg/kstatus/status/status_compute_test.go
  pkg/kstatus/status/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#91 New structure for the apply cmd
  cmd/apply/cmdapply.go
  cmd/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#73 Add status command
  cmd/main.go
  cmd/status/print/print.go
  cmd/status/printers/color.go
  cmd/status/printers/printers.go
  cmd/status/printers/table_printer.go
  cmd/status/status.go
  cmd/status/util.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#90 Simplify the StatusReaders and add better handling for resource types that act as controllers for pods
  pkg/kstatus/polling/engine/engine_test.go
  pkg/kstatus/polling/engine/status_reader.go
  pkg/kstatus/polling/statusreaders/common.go
  pkg/kstatus/polling/statusreaders/common_test.go
  pkg/kstatus/polling/statusreaders/deployment.go
  pkg/kstatus/polling/statusreaders/deployment_test.go
  pkg/kstatus/polling/statusreaders/generic.go
  pkg/kstatus/polling/statusreaders/generic_test.go
  pkg/kstatus/polling/statusreaders/pod_controller.go
  pkg/kstatus/polling/statusreaders/pod_controller_test.go
  pkg/kstatus/polling/statusreaders/replicaset.go
  pkg/kstatus/polling/statusreaders/replicaset_test.go
  pkg/kstatus/polling/statusreaders/statefulset.go
  pkg/kstatus/polling/statusreaders/statefulset_test.go
  pkg/kstatus/polling/statusreaders/testing.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#92 Accomodates cluster-scoped resources when validating namespace
  pkg/apply/applier.go
  pkg/apply/applier_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/M

#93 Move hard-coded default namespace to proper constants
  cmd/status/util.go
  pkg/config/initoptions.go
  pkg/kstatus/polling/statusreaders/common.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/S

#95 Fix issue that causes wait-for-reconcile to never finish
  pkg/apply/applier.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#96 Fix e2e tests
  examples/alphaTestExamples/helloapp.md
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/M

#94 Fixes validation problem with invalid label values
  pkg/config/initoptions.go
  pkg/config/initoptions_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/M

#97 Fixes grouping object namespace calculation
  pkg/config/initoptions.go
  pkg/config/initoptions_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/M

#100 Add make target for running e2e tests on prow
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#98 Update sorting of resources in Applier
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/prune/grouping.go
  pkg/apply/prune/grouping_test.go
  pkg/apply/prune/no_grouping_error.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#101 Fixes minor issue in init command and current directory (.)
  pkg/config/initoptions.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/S

#104 Close channel for StatusPoller after validation failures
  pkg/kstatus/polling/polling.go
  pkg/kstatus/polling/polling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#102 Implement the applier as a queue of tasks
  cmd/apply/cmdapply.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/poller/poller.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/prune_task.go
  pkg/apply/task/send_event_task.go
  pkg/apply/taskrunner/collector.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/runner_test.go
  pkg/apply/taskrunner/task.go
  pkg/apply/taskrunner/task_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#106 Default grouping label is a UUID
  go.mod
  pkg/config/initoptions.go
  pkg/config/initoptions_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cli, size/M

#105 Update the docs for the kstatus package
  pkg/kstatus/README.md
  pkg/kstatus/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#108 Fix some synchronization issues
  pkg/apply/printer_adapter_test.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/task.go
  pkg/apply/taskrunner/task_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#107 Add init event to Applier
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/event/event.go
  pkg/apply/event/resourceaction_string.go
  pkg/apply/event/type_string.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#112 BasicPrinter should only print status while waiting
  pkg/apply/basic_printer.go
Labels: approved, cncf-cla: yes, lgtm, size/L
