Repository kubernetes-sigs/cli-utils, pull requests merged in 2020-08, with the labels that each got.

#209 Adds e2e test for basic pruning functionality
  examples/alphaTestExamples/pruneBasic.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#211 Adds random suffix to legacy default inventory name
  pkg/common/common.go
  pkg/config/initoptions.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#210 Server side preview
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  cmd/printers/printer/printer.go
  cmd/printers/table/printer.go
  examples/alphaTestExamples/crds.md
  examples/alphaTestExamples/helloapp.md
  examples/alphaTestExamples/pruneAndDelete.md
  pkg/apply/applier.go
  pkg/apply/basic_printer.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/task/prune_task.go
  pkg/common/common.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, wg/api-expression

#212 Allow resources in multiple namespaces
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/inventory/inventory_error.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#213 Inventory client uses factory function
  pkg/apply/destroyer.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#214 Function to set inventory factory function on inventory client
  pkg/apply/applier.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#215 Bump kyaml version to v0.6.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#216 Fixes bug in destroy command
  pkg/apply/destroyer.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#206 Update status command to leverage inventory and add additional output formats
  cmd/main.go
  cmd/status/cmdstatus.go
  cmd/status/cmdstatus_test.go
  cmd/status/printers/event/event_printer.go
  cmd/status/printers/printer/printer.go
  cmd/status/printers/printers.go
  cmd/status/printers/table/adapter.go
  cmd/status/printers/table/table_printer.go
  cmd/status/printers/table_printer.go
  cmd/status/status.go
  cmd/status/util.go
  pkg/apply/applier.go
  pkg/inventory/fake-inventory-client.go
  pkg/kstatus/polling/collector/collector.go
  pkg/util/factory/statuspoller.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#217 Small destroyer fix removes unneeded code
  pkg/apply/destroyer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#218 Improve error handling
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/initcmd/cmdinit.go
  cmd/main.go
  cmd/preview/cmdpreview.go
  cmd/printers/printer/printer.go
  cmd/printers/table/collector.go
  cmd/printers/table/printer.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/basic_printer.go
  pkg/apply/destroyer.go
  pkg/apply/taskrunner/collector.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/runner_test.go
  pkg/apply/taskrunner/task.go
  pkg/errors/errors.go
  pkg/errors/errors_test.go
  pkg/print/table/base.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#219 Preview command refactored to use PreviewRunner
  cmd/main.go
  cmd/preview/cmdpreview.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#220 Destroy command refactored to use DestroyRunner
  cmd/destroy/cmddestroy.go
  cmd/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#222 Fix name of --inventory-namespace flag in init error message
  pkg/config/initoptions.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#221 Allow colon in the name of RBAC resources
  pkg/inventory/inventory_test.go
  pkg/object/objmetadata.go
  pkg/object/objmetadata_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#228 Pin to kyaml v0.7.0
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS

#229 Pin to kyaml v0.7.1
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS
