Repository kubernetes-sigs/cli-utils, pull requests merged in 2020-06, with the labels that each got.

#175 Expand stdin and filter inventory object for diff
  cmd/diff/cmddiff.go
  pkg/common/path.go
  pkg/common/path_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#184 Add support for CRDs in the status library
  examples/alphaTestExamples/crds.md
  pkg/kstatus/status/core.go
  pkg/kstatus/status/status_compute_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#183 Only mark pods as unschedulable if they have been in that state for a while
  pkg/kstatus/status/core.go
  pkg/kstatus/status/status_compute_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#171 First pass at inventory polymorphism POC
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/prune/inventory.go
  pkg/apply/prune/inventory_test.go
  pkg/apply/prune/inventorycm.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#177 Move the printer adapter into the ApplyTask
  pkg/apply/applier.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/printer_adapter.go
  pkg/apply/task/printer_adapter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#185 Export Applier within the ApplyRunner
  cmd/apply/cmdapply.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#186 Exports cobra command in ApplyRunner
  cmd/apply/cmdapply.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#181 Separate reading manifests into Info objects from the apply logic
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/manifestreader/common.go
  pkg/manifestreader/common_test.go
  pkg/manifestreader/path.go
  pkg/manifestreader/path_test.go
  pkg/manifestreader/stream.go
  pkg/manifestreader/stream_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#189 Initial move of Inventory to its own package
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_error.go
  pkg/inventory/inventory_test.go
  pkg/inventory/inventorycm.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#188 Simplify the InfoHelper and ApplyTask
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/info/info_helper.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/task/resetmapper_task.go
  pkg/apply/task/resetmapper_task_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#190 Creates InventoryClient to refactor prune
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#191 Creates helper function to create prune events
  pkg/apply/prune/prune.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#192 Use goreleaser to create github releases and capture release notes
  .github/workflows/main.yml
  release/goreleaser.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#195 Use sigs.k8s.io/yaml for YAML
  go.mod
  go.sum
  pkg/kstatus/status/status_compute_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
