Repository kubernetes-sigs/cli-utils, pull requests merged in 2020-12, with the labels that each got.

#292 Pin to kyaml v0.10.3
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#289 add inventory policy
  pkg/apply/applier.go
  pkg/apply/prune/prune.go
  pkg/inventory/policy.go
  pkg/inventory/policy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#291 enable InventoryPolicy in applier
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
  go.sum
  pkg/apply/applier.go
  pkg/apply/info/info_helper.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/task/prune_task.go
  pkg/inventory/policy.go
  pkg/inventory/policy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#279 CachingClusterReader should continue on all list errors
  pkg/kstatus/polling/clusterreader/caching_reader.go
  pkg/kstatus/polling/clusterreader/caching_reader_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#295 add test cases for applier
  pkg/apply/applier_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#296 Remove required setters check
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#304 Set up E2e tests with kind for the apply library
  Makefile
  go.mod
  go.sum
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#303 add ids in the apply task into taskContext
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#306 Pin to kyaml v0.10.4
  go.mod
  go.sum
  pkg/common/path_test.go
Labels: cncf-cla: yes, size/M

#305 Add more e2e tests for inventory policy
  test/e2e/apply_and_destroy_test.go
  test/e2e/common_test.go
  test/e2e/e2e_test.go
  test/e2e/inventory_policy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#307 Pin to kyaml v0.10.5
  go.mod
  go.sum
  pkg/common/path_test.go
Labels: cncf-cla: yes, size/M
