Repository kubernetes-sigs/cli-utils, pull requests merged in 2021-03, with the labels that each got.

#334 Pin cli-utils to kyaml v0.10.14
  Makefile
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M

#337 Upgrade k8s dependencies
  go.mod
  go.sum
  pkg/config/initoptions_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#338 Don't emit Prune event for NoMatchError
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S
