Repository kubernetes-sigs/cli-utils, pull requests merged in 2021-08, with the labels that each got.

#391 Remove some strings.TrimSpace() calls
  cmd/printers/events/formatter_test.go
  pkg/apply/applier.go
  pkg/apply/taskrunner/context.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_test.go
  pkg/inventory/inventorycm.go
  pkg/object/objmetadata.go
  pkg/object/objmetadata_test.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#394 Prune/Delete should use the specified propagation policy
  pkg/apply/applier.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#395 Move inventory annotation addition
  pkg/apply/applier.go
  pkg/apply/task/apply_task.go
Labels: approved, size/XS, lgtm, cncf-cla: yes

#396 Expose cyclic dependency error
  pkg/apply/applier.go
  pkg/apply/destroyer.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/object/graph/depends.go
  pkg/object/graph/depends_test.go
  pkg/object/graph/graph.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#399 Moves inventory policy check for apply into filter
  pkg/apply/applier.go
  pkg/apply/filter/inventory-policy-apply-filter.go
  pkg/apply/filter/inventory-policy-apply-filter_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes
