Repository kubernetes-sigs/cli-utils, pull requests merged in 2021-06, with the labels that each got.

#361 Update dependencies to Kubernetes v1.21.1
  .github/workflows/main.yml
  Makefile
  cmd/diff/cmddiff.go
  cmd/printers/table/collector.go
  examples/alphaTestExamples/inventoryNamespace.md
  examples/alphaTestExamples/pruneBasic.md
  examples/alphaTestExamples/pruneNamespace.md
  examples/alphaTestExamples/serverSideApply.md
  go.mod
  go.sum
  pkg/apply/applier.go
  pkg/apply/prune/prune.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/inv_add_task.go
  pkg/apply/task/inv_set_task.go
  pkg/common/path.go
  pkg/common/path_test.go
  pkg/config/initoptions.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory.go
  pkg/kstatus/polling/clusterreader/caching_reader_test.go
  scripts/check-everything.sh
  test/e2e/e2e_test.go
  test/e2e/serverside_apply_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#362 Simplify: remove unneeded meta.Accessor() usage
  pkg/apply/applier_test.go
  pkg/apply/prune/prune_test.go
  pkg/apply/task/inv_add_task.go
  pkg/inventory/inventory.go
  pkg/kstatus/polling/statusreaders/common.go
  pkg/manifestreader/common.go
  pkg/manifestreader/common_test.go
  pkg/manifestreader/path_test.go
  pkg/object/infos.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#363 Add comments to e2e test
  test/e2e/serverside_apply_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#365 Optimize sort
  pkg/ordering/sort.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#367 Object graph functionality
  pkg/object/graph/graph.go
  pkg/object/graph/graph_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#366 Refactor destroyer to use tasks
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/flagutils/utils.go
  examples/alphaTestExamples/MultipleServices.md
  examples/alphaTestExamples/helloapp.md
  examples/alphaTestExamples/pruneAndDelete.md
  pkg/apply/applier.go
  pkg/apply/destroyer.go
  pkg/apply/poller/poller.go
  pkg/apply/prune/event-factory.go
  pkg/apply/prune/event-factory_test.go
  pkg/apply/prune/prune.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/delete_inv_task.go
  pkg/apply/task/delete_inv_task_test.go
  pkg/apply/task/prune_task.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#368 Prune refactor to take objects to delete
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/testutil/events.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#355 Remove Applier.Initialize()
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/info/info_helper.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#369 Refactor prune/delete using ValidationFilter interface
  pkg/apply/applier.go
  pkg/apply/destroyer.go
  pkg/apply/filter/current-uids-filter.go
  pkg/apply/filter/current-uids-filter_test.go
  pkg/apply/filter/filter.go
  pkg/apply/filter/inventory-policy-filter.go
  pkg/apply/filter/inventory-policy-filter_test.go
  pkg/apply/filter/local-namespaces-filter.go
  pkg/apply/filter/local-namespaces-filter_test.go
  pkg/apply/filter/prevent-remove-filter.go
  pkg/apply/filter/prevent-remove-filter_test.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/task/prune_task.go
  pkg/apply/taskrunner/context.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#370 Remove Initialize() on Destroyer and PruneOptions
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/task/prune_task.go
  test/e2e/apply_and_destroy_test.go
  test/e2e/continue_on_error_test.go
  test/e2e/crd_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#371 Re-organizes pkg/object, adds annotation helpers
  pkg/apply/solver/solver.go
  pkg/manifestreader/common.go
  pkg/object/annotations.go
  pkg/object/annotations_test.go
  pkg/object/infos.go
  pkg/object/objmetadata.go
  pkg/object/unstructured.go
  pkg/object/unstructured_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#373 Adds Reason to ValidationFilter and skipped events
  pkg/apply/event/event.go
  pkg/apply/filter/current-uids-filter.go
  pkg/apply/filter/current-uids-filter_test.go
  pkg/apply/filter/filter.go
  pkg/apply/filter/inventory-policy-filter.go
  pkg/apply/filter/inventory-policy-filter_test.go
  pkg/apply/filter/local-namespaces-filter.go
  pkg/apply/filter/local-namespaces-filter_test.go
  pkg/apply/filter/prevent-remove-filter.go
  pkg/apply/filter/prevent-remove-filter_test.go
  pkg/apply/prune/event-factory.go
  pkg/apply/prune/event-factory_test.go
  pkg/apply/prune/prune.go
  pkg/inventory/policy.go
  pkg/inventory/policy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#374 Log statement at start of tasks
  pkg/apply/task/delete_inv_task.go
  pkg/apply/task/inv_add_task.go
  pkg/apply/task/inv_set_task.go
  pkg/apply/taskrunner/task.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#375 Adds object dependency sorting and tests
  pkg/apply/applier_test.go
  pkg/object/graph/depends.go
  pkg/object/graph/depends_test.go
  pkg/testutil/object.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#376 Destroyer calculates emit status events
  cmd/destroy/cmddestroy.go
  pkg/apply/applier.go
  pkg/apply/destroyer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#377 Inventory not found is not error during delete
  pkg/apply/task/delete_inv_task.go
  pkg/apply/task/delete_inv_task_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#372 Remove Provider interface
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/main.go
  cmd/preview/cmdpreview.go
  cmd/status/cmdstatus.go
  cmd/status/cmdstatus_test.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client-factory.go
  pkg/provider/fake-provider.go
  pkg/provider/provider.go
  test/e2e/customprovider/provider.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
