Repository kubernetes-sigs/cli-utils, pull requests merged in 2021-07, with the labels that each got.

#378 Better validation of resources prior to actuation
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/filter/local-namespaces-filter.go
  pkg/apply/prune/event-factory.go
  pkg/apply/prune/event-factory_test.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/task/inv_add_task.go
  pkg/apply/task/inv_add_task_test.go
  pkg/apply/task/inv_set_task_test.go
  pkg/apply/task/printer_adapter.go
  pkg/apply/task/prune_task.go
  pkg/inventory/inventory-client.go
  pkg/kstatus/polling/statusreaders/common.go
  pkg/kstatus/polling/statusreaders/deployment.go
  pkg/kstatus/polling/statusreaders/generic.go
  pkg/kstatus/polling/statusreaders/pod_controller.go
  pkg/kstatus/polling/statusreaders/testing.go
  pkg/manifestreader/common.go
  pkg/object/graph/depends.go
  pkg/object/graph/depends_test.go
  pkg/object/objmetadata.go
  pkg/object/unstructured.go
  pkg/object/unstructured_test.go
  pkg/object/validate.go
  pkg/object/validate_test.go
  pkg/ordering/sort.go
  pkg/testutil/events.go
  pkg/testutil/object.go
  test/e2e/continue_on_error_test.go
  test/e2e/crd_test.go
  test/e2e/inventory_policy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#380 Drop github.com/go-errors/errors and github.com/pkg/errors dependencies
  cmd/status/cmdstatus.go
  go.mod
  go.sum
  pkg/apply/destroyer.go
  pkg/kstatus/polling/engine/engine.go
  pkg/kstatus/status/generic.go
  pkg/kstatus/status/status.go
  pkg/object/validate.go
  pkg/util/factory/statuspoller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#381 Avoid referencing cmd line flags in error strings
  pkg/manifestreader/common.go
  pkg/manifestreader/common_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#385 Order by group kind
  pkg/ordering/sort.go
  pkg/ordering/sort_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#383 Add option for custom status readers
  pkg/kstatus/polling/polling.go
  pkg/kstatus/polling/statusreaders/generic.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#386 Drop gotest.tools dependency
  cmd/printers/table/collector_test.go
  go.mod
  go.sum
  pkg/apply/solver/solver_test.go
  pkg/apply/taskrunner/collector_test.go
  pkg/common/path_test.go
  pkg/kstatus/polling/aggregator/aggregator_test.go
  pkg/kstatus/polling/clusterreader/caching_reader_test.go
  pkg/kstatus/polling/collector/collector_test.go
  pkg/kstatus/polling/engine/engine_test.go
  pkg/kstatus/polling/event/event_test.go
  pkg/kstatus/polling/statusreaders/common_test.go
  pkg/kstatus/polling/statusreaders/generic_test.go
  pkg/kstatus/polling/statusreaders/pod_controller_test.go
  pkg/print/common/color_test.go
  pkg/print/table/base_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#384 Printers for status returns error
  cmd/status/cmdstatus.go
  cmd/status/printers/event/event_printer.go
  cmd/status/printers/printer/printer.go
  cmd/status/printers/table/table_printer.go
  pkg/kstatus/polling/collector/collector.go
  pkg/kstatus/polling/collector/collector_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#387 Avoid dryRun as state in inventory client
  cmd/status/cmdstatus.go
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/task/delete_inv_task.go
  pkg/apply/task/delete_inv_task_test.go
  pkg/apply/task/inv_add_task.go
  pkg/apply/task/inv_add_task_test.go
  pkg/apply/task/inv_set_task.go
  pkg/apply/task/inv_set_task_test.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#388 Moves apply failure inventory calculation into inventory task
  pkg/apply/solver/solver.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/task/inv_set_task.go
  pkg/apply/task/inv_set_task_test.go
  pkg/apply/taskrunner/context.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#389 Pass the RESTMapper explicitly into infoHelper
  pkg/apply/applier.go
  pkg/apply/info/info_helper.go
  pkg/inventory/inventory-client.go
Labels: approved, cncf-cla: yes, lgtm, size/S
