Repository kubernetes-sigs/cli-utils, pull requests merged in 2021-05, with the labels that each got.

#323 Fix a stale description in kstatus's README
  pkg/kstatus/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#349 Fix flaky applier test
  pkg/apply/applier_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#348 Use rand from apimachinery to avoid seeding rng every time
  pkg/common/common.go
  pkg/config/initoptions.go
  pkg/inventory/inventory.go
  test/e2e/common_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#339 Improve the event hierarchy
  cmd/printers/events/formatter.go
  cmd/printers/events/formatter_test.go
  cmd/printers/json/formatter.go
  cmd/printers/json/formatter_test.go
  cmd/printers/table/collector.go
  cmd/printers/table/collector_test.go
  cmd/printers/table/printer.go
  cmd/printers/table/printer_test.go
  examples/alphaTestExamples/crds.md
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/event/actiongroupeventtype_string.go
  pkg/apply/event/applyeventoperation_string.go
  pkg/apply/event/applyeventtype_string.go
  pkg/apply/event/deleteeventoperation_string.go
  pkg/apply/event/deleteeventtype_string.go
  pkg/apply/event/event.go
  pkg/apply/event/pruneeventoperation_string.go
  pkg/apply/event/pruneeventtype_string.go
  pkg/apply/event/resourceaction_string.go
  pkg/apply/event/statuseventtype_string.go
  pkg/apply/event/type_string.go
  pkg/apply/prune/prune.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/printer_adapter.go
  pkg/apply/task/printer_adapter_test.go
  pkg/apply/task/prune_task.go
  pkg/apply/taskrunner/collector.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/runner_test.go
  pkg/apply/taskrunner/task.go
  pkg/apply/taskrunner/task_test.go
  pkg/kstatus/polling/event/eventtype_string.go
  pkg/object/objmetadata.go
  pkg/print/list/base.go
  pkg/testutil/events.go
  test/e2e/apply_and_destroy_test.go
  test/e2e/common_test.go
  test/e2e/continue_on_error_test.go
  test/e2e/crd_test.go
  test/e2e/inventory_policy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#351 Don't cache nil mapper
  pkg/util/factory/clientgetter.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#352 More reusable BaseListPrinter
  cmd/printers/events/printer.go
  cmd/printers/json/printer.go
  cmd/printers/printers.go
  pkg/print/list/base.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#354 Reduce allocations in set operations
  pkg/object/objmetadata.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#353 Provide the DryRunStrategy through the destroyer options
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  pkg/apply/destroyer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#356 Use a specific error type when encountering unknown types
  pkg/errors/errors.go
  pkg/manifestreader/common.go
  pkg/manifestreader/common_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#359 Expose ManifestReader helper functions to users
  pkg/manifestreader/common.go
  pkg/manifestreader/common_test.go
  pkg/manifestreader/path.go
  pkg/manifestreader/stream.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#358 Move inventory operations into tasks
  go.sum
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/event/actiongroupeventtype_string.go
  pkg/apply/event/applyeventoperation_string.go
  pkg/apply/event/deleteeventoperation_string.go
  pkg/apply/event/event.go
  pkg/apply/event/pruneeventoperation_string.go
  pkg/apply/event/resourceaction_string.go
  pkg/apply/event/type_string.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/inv_add_task.go
  pkg/apply/task/inv_add_task_test.go
  pkg/apply/task/inv_set_task.go
  pkg/apply/task/inv_set_task_test.go
  pkg/apply/taskrunner/context.go
  pkg/kstatus/polling/event/eventtype_string.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
