Repository kubernetes-sigs/cli-utils, pull requests merged in 2021-10, with the labels that each got.

#416 Fix flaky continue on error test
  pkg/apply/event/event.go
  pkg/apply/prune/event-factory.go
  pkg/apply/prune/event-factory_test.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/task/printer_adapter.go
  pkg/apply/task/printer_adapter_test.go
  pkg/apply/task/prune_task.go
  pkg/testutil/events.go
  test/e2e/apply_and_destroy_test.go
  test/e2e/continue_on_error_test.go
  test/e2e/crd_test.go
  test/e2e/depends_on_test.go
  test/e2e/inventory_policy_test.go
  test/e2e/mutation_test.go
  test/e2e/prune_retrieve_error_test.go
Labels: approved, ok-to-test, lgtm, size/XXL, cncf-cla: yes

#456 fix: skipped deletes no longer cause waiting
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/task/inv_set_task.go
  pkg/apply/task/inv_set_task_test.go
  pkg/apply/taskrunner/condition_test.go
  pkg/apply/taskrunner/context.go
  pkg/apply/taskrunner/task.go
  pkg/object/objmetadata_set.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#458 Moves printers from cmd to pkg
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  pkg/printers/events/formatter.go
  pkg/printers/events/formatter_test.go
  pkg/printers/events/printer.go
  pkg/printers/json/doc.go
  pkg/printers/json/formatter.go
  pkg/printers/json/formatter_test.go
  pkg/printers/json/printer.go
  pkg/printers/printer/printer.go
  pkg/printers/printers.go
  pkg/printers/table/collector.go
  pkg/printers/table/collector_test.go
  pkg/printers/table/printer.go
  pkg/printers/table/printer_test.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#457 Removes inventory from manifestloader
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  cmd/status/cmdstatus.go
  cmd/status/cmdstatus_test.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_test.go
  pkg/manifestreader/manifestloader.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#451 Change the behavior of hanlding a WaitTask timeout
  pkg/apply/event/event.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/runner_test.go
  pkg/apply/taskrunner/task.go
  pkg/apply/taskrunner/task_test.go
  pkg/testutil/events.go
Labels: approved, size/L, lgtm, cncf-cla: yes
