Repository kubernetes-sigs/cli-utils, pull requests merged in 2021-02, with the labels that each got.

#319 Fix for final inventory update
  go.sum
  pkg/apply/applier.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#321 Remove special-case object name validation
  pkg/object/objmetadata.go
  pkg/object/objmetadata_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#322 Better final inventory calculation during errors
  pkg/apply/applier.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/taskrunner/context.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#324 Pin cli-utils to kyaml v0.10.7
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS

#325 Pin cli-utils to kyaml v0.10.9
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS

#301 Improve the Applier tests
  pkg/apply/applier_test.go
  pkg/inventory/inventory-client.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#326 Handle APIService speically when ServerSide apply is enabled
  go.sum
  pkg/apply/task/apply_task.go
  test/e2e/common_test.go
  test/e2e/e2e_test.go
  test/e2e/serverside_apply_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#327 Fix printing with continue-on-error
  cmd/printers/events/formatter.go
  cmd/printers/json/formatter.go
  pkg/print/list/base.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#328 Fix missing error property in PruneEventTransformer
  cmd/printers/events/formatter_test.go
  pkg/apply/destroyer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#330 Pin cli-utils to kyaml v0.10.12
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S

#332 Pin cli-utils to kyaml v0.10.13
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS
