Repository kubernetes-sigs/cli-utils, pull requests merged in 2021-01, with the labels that each got.

#308 Add e2e-tests for applying crd and cr at the same time
  test/e2e/apply_and_destroy_test.go
  test/e2e/common_test.go
  test/e2e/crd_test.go
  test/e2e/e2e_test.go
  test/e2e/inventory_policy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#309 Run apply-lib e2e tests on presubmit
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#302 allow pruning object without owning-inventory annotation
  pkg/inventory/policy.go
  pkg/inventory/policy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#310 Fix missing identifier delete event
  pkg/apply/destroyer.go
  test/e2e/crd_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#297 ingore the failed resources in wait task
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/prune_task.go
  pkg/apply/taskrunner/context.go
  pkg/apply/taskrunner/task.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#312 add e2e test for continue on error
  test/e2e/continue_on_error_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#315 Pin cliutils to kyaml v0.10.6
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS

#313 add apply flag: inventory-policy
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/flagutils/utils.go
  cmd/preview/cmdpreview.go
  pkg/apply/destroyer.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
  test/e2e/apply_and_destroy_test.go
  test/e2e/continue_on_error_test.go
  test/e2e/crd_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#316 add preprocess function in commands
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/flagutils/utils_test.go
  cmd/preview/cmdpreview.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#320 move inventory-policy flags and values to package level constants
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/flagutils/utils.go
  cmd/preview/cmdpreview.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#314 Fixes panic when id not found in collector
  cmd/printers/table/collector.go
  cmd/printers/table/collector_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
