Repository kubernetes-sigs/cli-utils, pull requests merged in 2021-11, with the labels that each got.

#459 Avoid printing out all the events
  pkg/apply/taskrunner/runner_test.go
Labels: approved, size/XS, lgtm, cncf-cla: yes

#430 Check versions a CRD defines
  pkg/manifestreader/common.go
  pkg/manifestreader/common_test.go
  pkg/object/unstructured.go
  pkg/object/unstructured_test.go
  pkg/object/validate_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#462 Removed unused command PreProcess function
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#464 Run `make all`
  pkg/apply/event/type_string.go
Labels: approved, size/XS, lgtm, cncf-cla: yes

#465 Exports Applier/Destroyer StatusPoller field
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/common_test.go
  pkg/apply/destroyer.go
  test/e2e/e2e_test.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#461 Cherry-pick two commits
  pkg/apply/event/event.go
  pkg/apply/event/type_string.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/runner_test.go
  pkg/apply/taskrunner/task.go
  pkg/apply/taskrunner/task_test.go
  pkg/testutil/events.go
Labels: approved, size/L, lgtm, tide/merge-method-squash, cncf-cla: yes

#468 fix: race condition in BuildInfo
  pkg/apply/task/apply_task.go
  pkg/object/infos.go
Labels: approved, size/XS, lgtm, cncf-cla: yes

#469 fix: race condition in PruneTask
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#463 feat: send WaitEvent for every resource
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer_test.go
  pkg/apply/event/event.go
  pkg/apply/event/waiteventoperation_string.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/delete_inv_task.go
  pkg/apply/task/inv_add_task.go
  pkg/apply/task/inv_set_task.go
  pkg/apply/task/prune_task.go
  pkg/apply/taskrunner/main_test.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/runner_test.go
  pkg/apply/taskrunner/task.go
  pkg/apply/taskrunner/task_test.go
  pkg/print/list/base.go
  pkg/printers/events/formatter.go
  pkg/printers/events/formatter_test.go
  pkg/printers/json/formatter.go
  pkg/printers/json/formatter_test.go
  pkg/printers/table/collector.go
  pkg/printers/table/printer.go
  pkg/testutil/events.go
  test/e2e/apply_and_destroy_test.go
  test/e2e/crd_test.go
  test/e2e/depends_on_test.go
  test/e2e/inventory_policy_test.go
  test/e2e/mutation_test.go
Labels: approved, lgtm, size/XXL, cncf-cla: yes

#474 No need to lowercase namespaces
  pkg/apply/applier.go
Labels: approved, size/XS, lgtm, cncf-cla: yes

#473 Add missing returns
  pkg/apply/applier.go
  pkg/apply/destroyer.go
Labels: approved, size/XS, lgtm, cncf-cla: yes

#470 feat: Add apply/destroy --status-events flag
  cmd/apply/cmdapply.go
  cmd/destroy/cmddestroy.go
  examples/alphaTestExamples/MultipleServices.md
  examples/alphaTestExamples/crds.md
  examples/alphaTestExamples/helloapp.md
Labels: approved, size/M, lgtm, cncf-cla: yes

#472 Consistently use InfoHelper to get rest client
  pkg/apply/info/info_helper.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#475 fix: Improve task & event logging
  pkg/apply/event/event.go
  pkg/apply/prune/prune.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/delete_inv_task.go
  pkg/apply/task/inv_add_task.go
  pkg/apply/task/inv_set_task.go
  pkg/apply/task/prune_task.go
  pkg/apply/task/send_event_task.go
  pkg/apply/taskrunner/context.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/runner_test.go
  pkg/apply/taskrunner/task.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#477 fix: Ensure WaitTask gets StatusUpdate
  pkg/apply/taskrunner/runner.go
Labels: approved, size/XS, lgtm, cncf-cla: yes

#476 fix: Add context & timeouts to e2e tests
  test/e2e/apply_and_destroy_test.go
  test/e2e/common_test.go
  test/e2e/continue_on_error_test.go
  test/e2e/crd_test.go
  test/e2e/deletion_prevention_test.go
  test/e2e/depends_on_test.go
  test/e2e/e2e_test.go
  test/e2e/inventory_policy_test.go
  test/e2e/mutation_test.go
  test/e2e/name_inv_strategy_test.go
  test/e2e/prune_retrieve_error_test.go
  test/e2e/serverside_apply_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#449 feat: Always wait for reconciliation
  pkg/apply/applier_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/taskrunner/runner_test.go
  pkg/apply/taskrunner/task.go
  pkg/apply/taskrunner/task_test.go
  pkg/object/graph/depends.go
  pkg/testutil/events.go
  test/e2e/apply_and_destroy_test.go
  test/e2e/continue_on_error_test.go
  test/e2e/deletion_prevention_test.go
  test/e2e/e2e_test.go
  test/e2e/prune_retrieve_error_test.go
Labels: approved, lgtm, size/XXL, cncf-cla: yes

#471 fix: Colorize example tests
  examples/alphaTestExamples/MultipleServices.md
  examples/alphaTestExamples/crds.md
  examples/alphaTestExamples/helloapp.md
  examples/alphaTestExamples/init.md
  examples/alphaTestExamples/inventoryNamespace.md
  examples/alphaTestExamples/pruneAndDelete.md
  examples/alphaTestExamples/pruneBasic.md
  examples/alphaTestExamples/pruneNamespace.md
  examples/alphaTestExamples/serverSideApply.md
  hack/testExamplesE2EAgainstKapply.sh
Labels: approved, size/L, lgtm, cncf-cla: yes

#478 fix: Make testutil.AssertEqual more like testify
  pkg/apply/applier_test.go
  pkg/apply/destroyer_test.go
  pkg/apply/task/inv_set_task_test.go
  pkg/apply/taskrunner/task_test.go
  pkg/testutil/matcher.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#479 fix: Make UnknownTypesError error more readable
  pkg/manifestreader/common.go
Labels: approved, size/XS, lgtm, cncf-cla: yes
