Repository kubernetes-sigs/cli-utils, pull requests merged in 2022-01, with the labels that each got.

#504 json printer should only print stats after last action group per type
  pkg/printers/json/formatter.go
  pkg/printers/json/formatter_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#501 fix: Remove preview/dry-run type from events output
  cmd/preview/cmdpreview.go
  examples/alphaTestExamples/helloapp.md
  examples/alphaTestExamples/pruneAndDelete.md
  pkg/printers/events/formatter.go
  pkg/printers/events/formatter_test.go
  pkg/printers/json/formatter.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#506 fix: Handle more validation errors as field errors
  pkg/apply/mutator/apply_time_mutator_test.go
  pkg/object/field.go
  pkg/object/field_test.go
  pkg/object/unstructured.go
  pkg/object/validate.go
  pkg/object/validate_test.go
  pkg/testutil/unstructured.go
  test/e2e/depends_on_test.go
  test/e2e/inventory_policy_test.go
  test/e2e/mutation_test.go
  test/e2e/prune_retrieve_error_test.go
  test/e2e/serverside_apply_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#507 fix: Clean up object.FieldPath
  pkg/object/field.go
  pkg/object/field_test.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#505 fix: Don't panic when ObjMetadata is invalid (missing kind/name)
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/cache/resource_cache.go
  pkg/apply/cache/resource_cache_map.go
  pkg/apply/common_test.go
  pkg/apply/destroyer.go
  pkg/apply/filter/inventory-policy-apply-filter.go
  pkg/apply/filter/local-namespaces-filter.go
  pkg/apply/prune/event-factory.go
  pkg/apply/prune/event-factory_test.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/task/inv_add_task.go
  pkg/apply/task/inv_add_task_test.go
  pkg/apply/task/inv_set_task_test.go
  pkg/apply/task/prune_task.go
  pkg/apply/taskrunner/condition_test.go
  pkg/inventory/inventory-client.go
  pkg/kstatus/polling/statusreaders/deployment.go
  pkg/kstatus/polling/statusreaders/generic.go
  pkg/kstatus/polling/statusreaders/pod_controller.go
  pkg/kstatus/polling/statusreaders/testing.go
  pkg/object/dependson/strings.go
  pkg/object/graph/depends.go
  pkg/object/graph/depends_test.go
  pkg/object/infos.go
  pkg/object/mutation/types.go
  pkg/object/objmetadata.go
  pkg/object/objmetadata_test.go
  pkg/object/unstructured.go
  pkg/object/unstructured_test.go
  pkg/ordering/sort.go
  test/e2e/apply_and_destroy_test.go
  test/e2e/common_test.go
  test/e2e/continue_on_error_test.go
  test/e2e/crd_test.go
  test/e2e/customprovider/provider.go
  test/e2e/depends_on_test.go
  test/e2e/inventory_policy_test.go
  test/e2e/mutation_test.go
  test/e2e/prune_retrieve_error_test.go
  test/e2e/reconcile_failed_timeout_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#500 feat: Return a specific error type from the printers when resources fail to apply/delete/reconcile
  pkg/print/common/errors.go
  pkg/print/list/base.go
  pkg/print/list/base_test.go
  pkg/print/stats/stats.go
  pkg/printers/events/formatter.go
  pkg/printers/events/formatter_test.go
  pkg/printers/json/formatter.go
  pkg/printers/json/formatter_test.go
  pkg/printers/table/collector.go
  pkg/printers/table/printer.go
  pkg/printers/table/printer_test.go
  pkg/printers/testutil/common.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#508 feat: MultiError for invalid annotations
  pkg/apply/applier.go
  pkg/apply/mutator/apply_time_mutator.go
  pkg/apply/mutator/apply_time_mutator_test.go
  pkg/inventory/inventory-client.go
  pkg/jsonpath/jsonpath.go
  pkg/multierror/multierror.go
  pkg/object/dependson/annotation.go
  pkg/object/dependson/strings.go
  pkg/object/graph/depends.go
  pkg/object/graph/depends_test.go
  pkg/object/graph/graph.go
  pkg/object/mutation/annotation.go
  pkg/object/mutation/types.go
  pkg/object/validate.go
  pkg/object/validate_test.go
  pkg/object/validation/error.go
  pkg/object/validation/validate.go
  pkg/object/validation/validate_test.go
  test/e2e/artifacts_test.go
  test/e2e/common_test.go
  test/e2e/e2e_test.go
  test/e2e/mutation_test.go
Labels: approved, lgtm, size/XXL, cncf-cla: yes

#510 fix: Update ObjMetadataSet.Hash to not error
  pkg/object/objmetadata_set.go
  pkg/object/objmetadata_set_test.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#511 fix: Merge task runner impls into taskStatusRunner
  pkg/apply/applier.go
  pkg/apply/destroyer.go
  pkg/apply/event/event.go
  pkg/apply/event/resourceaction_string.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/runner_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#512 fix: Make CyclicDependencyError edges stable
  pkg/apply/solver/solver_test.go
  pkg/object/graph/graph.go
  pkg/object/graph/graph_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#497 Update dependencies to Kubernetes v1.23.1
  cmd/main.go
  go.mod
  go.sum
  pkg/object/infos.go
  pkg/object/infos_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#513 fix: Improve solver tests
  pkg/apply/solver/main_test.go
  pkg/apply/solver/solver_test.go
  pkg/apply/taskrunner/task.go
  pkg/testutil/asserter.go
  pkg/testutil/matcher.go
  pkg/testutil/restmapper.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#516 fix: Remove support for multiple inventory objects with the same inventory id
  cmd/status/cmdstatus.go
  pkg/apply/prune/prune.go
  pkg/apply/solver/solver.go
  pkg/apply/task/inv_add_task_test.go
  pkg/apply/task/inv_set_task_test.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#517 fix: remove reflection hack
  cmd/main.go
  pkg/apply/taskrunner/task.go
  pkg/util/factory/clientgetter.go
  test/e2e/e2e_test.go
Labels: kind/bug, approved, size/M, lgtm, cncf-cla: yes

#515 fix: Use the dynamic client in the InventoryClient
  pkg/apply/common_test.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
  pkg/object/infos.go
  pkg/object/unstructured.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#488 feat: Add ValidationPolicy & ValidationEvent
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/common_test.go
  pkg/apply/destroyer.go
  pkg/apply/event/event.go
  pkg/apply/event/type_string.go
  pkg/apply/mutator/apply_time_mutator_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/task/inv_set_task.go
  pkg/apply/task/inv_set_task_test.go
  pkg/apply/taskrunner/context.go
  pkg/object/dependson/annotation.go
  pkg/object/dependson/strings.go
  pkg/object/error.go
  pkg/object/error_test.go
  pkg/object/graph/depends.go
  pkg/object/graph/depends_test.go
  pkg/object/graph/edge.go
  pkg/object/graph/edge_test.go
  pkg/object/graph/error.go
  pkg/object/graph/error_test.go
  pkg/object/graph/graph.go
  pkg/object/graph/graph_test.go
  pkg/object/mutation/annotation.go
  pkg/object/objmetadata_set.go
  pkg/object/validation/collector.go
  pkg/object/validation/policy.go
  pkg/object/validation/policy_string.go
  pkg/object/validation/validate.go
  pkg/object/validation/validate_test.go
  pkg/print/list/base.go
  pkg/print/list/base_test.go
  pkg/printers/events/formatter.go
  pkg/printers/events/formatter_test.go
  pkg/printers/json/formatter.go
  pkg/printers/json/formatter_test.go
  pkg/printers/table/collector.go
  pkg/printers/table/collector_test.go
  pkg/testutil/events.go
  test/e2e/artifacts_test.go
  test/e2e/common_test.go
  test/e2e/e2e_test.go
  test/e2e/exit_early_test.go
  test/e2e/skip_invalid_test.go
Labels: approved, lgtm, size/XXL, cncf-cla: yes

#520 Avoid goroutine being blocked forever in WaitTask
  pkg/apply/taskrunner/task.go
  pkg/apply/taskrunner/task_test.go
Labels: size/S, approved, lgtm, cncf-cla: yes
