Repository kubernetes-sigs/cli-utils, pull requests merged in 2022-06, with the labels that each got.

#588 fix: make deletion idempotent
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/task/apply_task.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#589 chore: Update readme with features and packages
  README.md
Labels: approved, size/L, lgtm, cncf-cla: yes

#592 update owner file
  OWNERS
Labels: approved, size/XS, lgtm, cncf-cla: yes

#593 fix: Always apply status when merging or replacing
  pkg/inventory/inventory-client.go
Labels: size/S, approved, ok-to-test, lgtm, cncf-cla: yes
