Repository kubernetes-sigs/cli-utils, pull requests merged in 2022-02, with the labels that each got.

#485 Applier constructor and run: builder
  cmd/apply/cmdapply.go
  cmd/preview/cmdpreview.go
  pkg/apply/applier.go
  pkg/apply/applier_builder.go
  pkg/apply/applier_test.go
  pkg/apply/common_test.go
  pkg/apply/destroyer.go
  pkg/apply/info/info_helper.go
  pkg/apply/poller/poller.go
  pkg/apply/solver/solver.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  test/e2e/apply_and_destroy_test.go
  test/e2e/continue_on_error_test.go
  test/e2e/crd_test.go
  test/e2e/deletion_prevention_test.go
  test/e2e/depends_on_test.go
  test/e2e/e2e_test.go
  test/e2e/exit_early_test.go
  test/e2e/inventory_policy_test.go
  test/e2e/mutation_test.go
  test/e2e/name_inv_strategy_test.go
  test/e2e/prune_retrieve_error_test.go
  test/e2e/reconcile_failed_timeout_test.go
  test/e2e/serverside_apply_test.go
  test/e2e/skip_invalid_test.go
Labels: approved, kind/cleanup, lgtm, size/XL, cncf-cla: yes

#521 Fixes lint error
  test/e2e/common_test.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#514 capture the apply status in the inventory object
  pkg/apply/event/actiongroupeventtype_string.go
  pkg/apply/event/applyeventoperation_string.go
  pkg/apply/event/deleteeventoperation_string.go
  pkg/apply/event/pruneeventoperation_string.go
  pkg/apply/event/resourceaction_string.go
  pkg/apply/event/type_string.go
  pkg/apply/event/waiteventoperation_string.go
  pkg/apply/prune/prune_test.go
  pkg/apply/task/inv_set_task.go
  pkg/common/dryrunstrategy_string.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_test.go
  pkg/inventory/inventorycm.go
  pkg/inventory/inventoryidmatchstatus_string.go
  pkg/inventory/inventorypolicy_string.go
  pkg/kstatus/polling/event/eventtype_string.go
  pkg/kstatus/status/apply_status.go
  pkg/kstatus/status/applystatus_string.go
  pkg/kstatus/status/reconcilestatus_string.go
  pkg/object/validation/policy_string.go
  test/e2e/customprovider/provider.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#525 Revert "capture the apply/reconcile status in the inventory object"
  pkg/apply/event/actiongroupeventtype_string.go
  pkg/apply/event/applyeventoperation_string.go
  pkg/apply/event/deleteeventoperation_string.go
  pkg/apply/event/pruneeventoperation_string.go
  pkg/apply/event/resourceaction_string.go
  pkg/apply/event/type_string.go
  pkg/apply/event/waiteventoperation_string.go
  pkg/apply/prune/prune_test.go
  pkg/apply/task/inv_set_task.go
  pkg/common/dryrunstrategy_string.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_test.go
  pkg/inventory/inventorycm.go
  pkg/inventory/inventoryidmatchstatus_string.go
  pkg/inventory/inventorypolicy_string.go
  pkg/kstatus/polling/event/eventtype_string.go
  pkg/kstatus/status/apply_status.go
  pkg/kstatus/status/applystatus_string.go
  pkg/kstatus/status/reconcilestatus_string.go
  pkg/object/validation/policy_string.go
  test/e2e/customprovider/provider.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#519 Expose ClusterReader options in the API
  cmd/status/cmdstatus.go
  cmd/status/cmdstatus_test.go
  pkg/apply/applier.go
  pkg/apply/applier_builder.go
  pkg/apply/common_test.go
  pkg/apply/destroyer.go
  pkg/apply/poller/poller.go
  pkg/apply/taskrunner/runner.go
  pkg/apply/taskrunner/runner_test.go
  pkg/kstatus/polling/clusterreader/caching_reader.go
  pkg/kstatus/polling/clusterreader/caching_reader_test.go
  pkg/kstatus/polling/clusterreader/direct_reader.go
  pkg/kstatus/polling/doc.go
  pkg/kstatus/polling/engine/engine.go
  pkg/kstatus/polling/engine/engine_test.go
  pkg/kstatus/polling/polling.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#531 chore: Add Inventory to TaskContext
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/task/apply_task.go
  pkg/apply/task/apply_task_test.go
  pkg/apply/task/inv_set_task.go
  pkg/apply/task/inv_set_task_test.go
  pkg/apply/task/prune_task.go
  pkg/apply/taskrunner/condition.go
  pkg/apply/taskrunner/condition_test.go
  pkg/apply/taskrunner/context.go
  pkg/apply/taskrunner/task.go
  pkg/apply/taskrunner/task_test.go
  pkg/inventory/actuationstatus_string.go
  pkg/inventory/actuationstrategy_string.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory.go
  pkg/inventory/inventorycm.go
  pkg/inventory/manager.go
  pkg/inventory/reconcilestatus_string.go
  pkg/inventory/type-conv.go
  pkg/inventory/types.go
  test/e2e/customprovider/provider.go
Labels: approved, lgtm, size/XXL, cncf-cla: yes

#539 fix: Handle async object replacement
  pkg/apply/taskrunner/task.go
  pkg/apply/taskrunner/task_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#541 chore: Move AdoptAll logic out of the Applier
  pkg/apply/applier.go
  pkg/apply/filter/inventory-policy-apply-filter.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#540 Use discovery client to check if inventory objects has subresource status
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#543 chore: Remove redundant object sorting
  pkg/apply/applier.go
  pkg/apply/prune/prune.go
Labels: approved, size/XS, lgtm, cncf-cla: yes

#544 chore: Log YAML to V7, instead of V4
  pkg/apply/mutator/apply_time_mutator.go
  pkg/apply/mutator/apply_time_mutator_test.go
  pkg/object/mutation/annotation.go
  pkg/object/mutation/types.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#542 chore: Move Inventory object to pkg/apis/actuation
  LICENSE_TEMPLATE_GO
  Makefile
  hack/run-in-gopath.sh
  pkg/apis/actuation/actuationstatus_string.go
  pkg/apis/actuation/actuationstrategy_string.go
  pkg/apis/actuation/doc.go
  pkg/apis/actuation/reconcilestatus_string.go
  pkg/apis/actuation/types.go
  pkg/apis/actuation/zz_generated.deepcopy.go
  pkg/apply/taskrunner/task_test.go
  pkg/inventory/manager.go
  pkg/inventory/type-conv.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#546 fix: Always copy ResourceVersion before update
  pkg/apply/common_test.go
  pkg/inventory/inventory-client.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#547 Don't store Context inside a struct, pass it explicitly to each function that needs it.
  pkg/kstatus/polling/engine/engine.go
Labels: size/S, approved, ok-to-test, lgtm, cncf-cla: yes

#530 capture the apply/reconcile status in the inventory object
  pkg/apply/prune/prune_test.go
  pkg/apply/task/inv_set_task.go
  pkg/inventory/fake-inventory-client.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_test.go
  pkg/inventory/inventorycm.go
  pkg/inventory/inventorycm_test.go
  test/e2e/customprovider/provider.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#552 fix: Don't error if inventory namespace already exists
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
  pkg/inventory/inventory_test.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#550 Ensure that Daemonset controller has acted on the Daemonset.
  pkg/kstatus/status/core.go
  pkg/kstatus/status/status_compute_test.go
Labels: approved, size/M, ok-to-test, lgtm, cncf-cla: yes

#549 chore: Change solver to decide which tasks to use
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#556 fix: Inventory.SetObjectStatus
  pkg/apply/task/inv_set_task_test.go
  pkg/inventory/manager.go
  pkg/inventory/manager_test.go
  pkg/inventory/type-conv.go
Labels: approved, size/L, lgtm, cncf-cla: yes
