Repository kubernetes-sigs/cli-utils, pull requests merged in 2022-11, with the labels that each got.

#608 chore: Bump golangci-lint version
  .golangci.yml
  Makefile
  cmd/diff/cmddiff.go
  pkg/apply/common_test.go
  pkg/apply/event/event.go
  pkg/apply/prune/event-factory.go
  pkg/apply/prune/prune.go
  pkg/apply/task/apply_task.go
  pkg/apply/taskrunner/runner.go
  pkg/common/common.go
  pkg/common/path.go
  pkg/common/path_test.go
  pkg/config/initoptions.go
  pkg/config/initoptions_test.go
  pkg/flowcontrol/flowcontrol_test.go
  pkg/inventory/configmap/cm-template.go
  pkg/inventory/fake-builder.go
  pkg/inventory/policy.go
  pkg/inventory/status-policy.go
  pkg/kstatus/polling/aggregator/aggregator.go
  pkg/kstatus/polling/doc.go
  pkg/kstatus/status/doc.go
  pkg/kstatus/status/status.go
  pkg/kstatus/watcher/doc.go
  pkg/kstatus/watcher/object_status_reporter.go
  pkg/manifestreader/manifestloader_test.go
  pkg/manifestreader/path_test.go
  pkg/object/dependson/strings.go
  pkg/object/graph/graph_test.go
  pkg/object/objmetadata.go
  pkg/print/list/base.go
  pkg/printers/json/doc.go
  pkg/printers/table/printer.go
  pkg/testutil/test-filesystem.go
Labels: approved, ok-to-test, size/L, lgtm, cncf-cla: yes

#609 chore: Update Go to v1.18
  .github/workflows/main.yml
  go.mod
  go.sum
Labels: approved, size/M, ok-to-test, lgtm, cncf-cla: yes

#606 Update dependencies to Kubernetes v1.25.3
  Makefile
  go.mod
  go.sum
  hack/old_dot_travis
  pkg/common/path_test.go
  pkg/kstatus/polling/clusterreader/caching_reader_test.go
  pkg/kstatus/watcher/dynamic_informer_factory.go
  pkg/kstatus/watcher/dynamic_informer_factory_test.go
  pkg/kstatus/watcher/object_status_reporter.go
  test/e2e/e2e_test.go
  test/stress/stress_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes
