Repository kubernetes-sigs/cli-utils, pull requests merged in 2022-03, with the labels that each got.

#555 feat: Add dependency filter
  pkg/apply/applier.go
  pkg/apply/destroyer.go
  pkg/apply/filter/dependency-filter.go
  pkg/apply/filter/dependency-filter_test.go
  pkg/apply/filter/relationship_string.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  pkg/apply/taskrunner/context.go
  pkg/inventory/manager.go
  pkg/object/graph/depends.go
  pkg/object/graph/depends_test.go
  pkg/object/graph/graph.go
  pkg/object/graph/graph_test.go
  test/e2e/artifacts_test.go
  test/e2e/dependency_filter_test.go
  test/e2e/e2e_test.go
  test/e2e/namespace_filter_test.go
Labels: approved, lgtm, size/XXL, cncf-cla: yes

#558 fix: Make DependencyFilter handle DryRun
  pkg/apply/applier.go
  pkg/apply/destroyer.go
  pkg/apply/filter/dependency-filter.go
  pkg/apply/filter/dependency-filter_test.go
  test/e2e/dry_run_test.go
  test/e2e/e2e_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#560 fix: Allow empty set of apply objects
  pkg/apply/applier_test.go
  pkg/apply/solver/solver.go
  pkg/apply/solver/solver_test.go
  test/e2e/e2e_test.go
  test/e2e/empty_set_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#563 feat: Add inventory.StatusPolicy
  pkg/inventory/inventory-client-factory.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
  pkg/inventory/status-policy.go
  pkg/inventory/statuspolicy_string.go
  test/e2e/apply_and_destroy_test.go
  test/e2e/customprovider/provider.go
  test/e2e/deletion_prevention_test.go
  test/e2e/dry_run_test.go
  test/e2e/e2e_test.go
  test/e2e/empty_set_test.go
  test/e2e/inventory_policy_test.go
  test/e2e/name_inv_strategy_test.go
  test/e2e/prune_retrieve_error_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#564 fix: Avoid logging UID error for skipped apply
  pkg/apply/taskrunner/task.go
Labels: approved, size/XS, lgtm, cncf-cla: yes

#566 Use empty object status list when the StatusPolicyNone is used
  cmd/main.go
  pkg/apply/common_test.go
  pkg/inventory/inventory-client.go
  pkg/inventory/inventory-client_test.go
  pkg/inventory/inventorycm.go
  pkg/inventory/inventorycm_test.go
  test/e2e/e2e_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#567 feat: pagninate status poller lists
  pkg/kstatus/polling/clusterreader/caching_reader.go
  pkg/kstatus/polling/clusterreader/caching_reader_test.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#562 feat: expose skip reason as error
  examples/alphaTestExamples/pruneAndDelete.md
  examples/alphaTestExamples/pruneNamespace.md
  pkg/apply/applier.go
  pkg/apply/applier_test.go
  pkg/apply/destroyer.go
  pkg/apply/event/event.go
  pkg/apply/filter/current-uids-filter.go
  pkg/apply/filter/current-uids-filter_test.go
  pkg/apply/filter/dependency-filter.go
  pkg/apply/filter/dependency-filter_test.go
  pkg/apply/filter/fatal_error.go
  pkg/apply/filter/filter.go
  pkg/apply/filter/inventory-policy-apply-filter.go
  pkg/apply/filter/inventory-policy-apply-filter_test.go
  pkg/apply/filter/inventory-policy-filter.go
  pkg/apply/filter/inventory-policy-prune-filter.go
  pkg/apply/filter/inventory-policy-prune-filter_test.go
  pkg/apply/filter/local-namespaces-filter.go
  pkg/apply/filter/local-namespaces-filter_test.go
  pkg/apply/filter/phase_string.go
  pkg/apply/filter/prevent-remove-filter.go
  pkg/apply/filter/prevent-remove-filter_test.go
  pkg/apply/prune/event-factory.go
  pkg/apply/prune/event-factory_test.go
  pkg/apply/prune/prune.go
  pkg/apply/prune/prune_test.go
  pkg/apply/task/apply_task.go
  pkg/errors/errors_test.go
  pkg/inventory/inventory.go
  pkg/inventory/inventory_error.go
  pkg/inventory/policy.go
  pkg/inventory/policy_test.go
  pkg/print/stats/stats.go
  pkg/printers/events/formatter.go
  pkg/printers/events/formatter_test.go
  pkg/printers/json/formatter.go
  pkg/printers/json/formatter_test.go
  pkg/testutil/matcher.go
  pkg/testutil/object.go
  test/e2e/dependency_filter_test.go
  test/e2e/e2e_test.go
  test/e2e/inventory_policy_test.go
  test/e2e/namespace_filter_test.go
Labels: approved, lgtm, size/XXL, cncf-cla: yes
