Repository kubernetes-sigs/cli-utils, pull requests merged in 2024-05, with the labels that each got.

#637 Add conversion func for status-policy
  cmd/flagutils/utils.go
Labels: size/S, approved, ok-to-test, lgtm, cncf-cla: yes

#639 Add status watch label filter
  pkg/apply/applier_builder.go
  pkg/apply/builder.go
  pkg/kstatus/watcher/default_status_watcher.go
  pkg/kstatus/watcher/default_status_watcher_test.go
  pkg/kstatus/watcher/dynamic_informer_factory.go
  pkg/kstatus/watcher/dynamic_informer_factory_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#640 Add WithStatusWatcherFilters to DestroyerBuilder
  pkg/apply/destroyer_builder.go
Labels: approved, size/XS, lgtm, cncf-cla: yes
